### ISSUE TITLE
Crashes unity when played->stopped->played again

### ISSUE THREAD

**Issue by PennyS2W** [SethGibson/CEF_01#1]
Great project, thank you. But when I hit the play button on SCN_Main, hit play again to stop then hit play for a third time to restart, it crashes Unity. 

Using Unity 5.3.4f1 x64

**Comment by SethGibson** [comment]
This is a known issue with CEF (actually with Chromium) having to do with how it manages memory and internal global objects. This could be potentially solved by regenerating the bindings for CefGlue to use dynamic loading, but that's outside the scope of this project.

**Comment by TheModdersDen** [comment]
I've submitted this as a bug report to the Unity3d team. They've contacted me back and said that they've sent it to their developers to fix. I don't know if that'll fix it entirely, but... it's a start. Also, is this project still in development or being worked on? Just wondering...
You can find the bug report/reply here: https://fogbugz.unity3d.com/default.asp?859622_u8is2f3be8bc0dlp
😄

**Comment by petersvp** [comment]
For production, it will be good idea if this is addressed.
